/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiariesRouteImport } from './routes/_authenticated/diaries'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated/integration'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedNavRouteImport } from './routes/_authenticated/nav'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPagesPageRouteImport } from './routes/_authenticated/pages.$page'
import { Route as ApiPublicContentNavRouteImport } from './routes/api/public/content/nav'
import { Route as ApiPublicContentSiteSettingsRouteImport } from './routes/api/public/content/site-settings'
import { Route as ApiPublicDiariesIndexRouteImport } from './routes/api/public/diaries/index'
import { Route as ApiPublicProductsIndexRouteImport } from './routes/api/public/products/index'
import { Route as ApiPublicProductsSlugRouteImport } from './routes/api/public/products/$slug'
import { Route as ApiPublicContentPagePageKeyRouteImport } from './routes/api/public/content/page.$pageKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiariesRoute = AuthenticatedDiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNavRoute = AuthenticatedNavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagesPageRoute = AuthenticatedPagesPageRouteImport.update({
  id: '/pages/$page',
  path: '/pages/$page',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicContentNavRoute = ApiPublicContentNavRouteImport.update({
  id: '/api/public/content/nav',
  path: '/api/public/content/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContentSiteSettingsRoute =
  ApiPublicContentSiteSettingsRouteImport.update({
    id: '/api/public/content/site-settings',
    path: '/api/public/content/site-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiariesIndexRoute = ApiPublicDiariesIndexRouteImport.update({
  id: '/api/public/diaries/',
  path: '/api/public/diaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsIndexRoute = ApiPublicProductsIndexRouteImport.update({
  id: '/api/public/products/',
  path: '/api/public/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSlugRoute = ApiPublicProductsSlugRouteImport.update({
  id: '/api/public/products/$slug',
  path: '/api/public/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContentPagePageKeyRoute =
  ApiPublicContentPagePageKeyRouteImport.update({
    id: '/api/public/content/page/$pageKey',
    path: '/api/public/content/page/$pageKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diaries': typeof AuthenticatedDiariesRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/media': typeof AuthenticatedMediaRoute
  '/nav': typeof AuthenticatedNavRoute
  '/products': typeof AuthenticatedProductsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pages/$page': typeof AuthenticatedPagesPageRoute
  '/api/public/content/nav': typeof ApiPublicContentNavRoute
  '/api/public/content/site-settings': typeof ApiPublicContentSiteSettingsRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/diaries/': typeof ApiPublicDiariesIndexRoute
  '/api/public/products/': typeof ApiPublicProductsIndexRoute
  '/api/public/content/page/$pageKey': typeof ApiPublicContentPagePageKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diaries': typeof AuthenticatedDiariesRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/media': typeof AuthenticatedMediaRoute
  '/nav': typeof AuthenticatedNavRoute
  '/products': typeof AuthenticatedProductsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pages/$page': typeof AuthenticatedPagesPageRoute
  '/api/public/content/nav': typeof ApiPublicContentNavRoute
  '/api/public/content/site-settings': typeof ApiPublicContentSiteSettingsRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/diaries': typeof ApiPublicDiariesIndexRoute
  '/api/public/products': typeof ApiPublicProductsIndexRoute
  '/api/public/content/page/$pageKey': typeof ApiPublicContentPagePageKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diaries': typeof AuthenticatedDiariesRoute
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/nav': typeof AuthenticatedNavRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/pages/$page': typeof AuthenticatedPagesPageRoute
  '/api/public/content/nav': typeof ApiPublicContentNavRoute
  '/api/public/content/site-settings': typeof ApiPublicContentSiteSettingsRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/diaries/': typeof ApiPublicDiariesIndexRoute
  '/api/public/products/': typeof ApiPublicProductsIndexRoute
  '/api/public/content/page/$pageKey': typeof ApiPublicContentPagePageKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/diaries'
    | '/integration'
    | '/media'
    | '/nav'
    | '/products'
    | '/seo'
    | '/settings'
    | '/pages/$page'
    | '/api/public/content/nav'
    | '/api/public/content/site-settings'
    | '/api/public/products/$slug'
    | '/api/public/diaries/'
    | '/api/public/products/'
    | '/api/public/content/page/$pageKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/diaries'
    | '/integration'
    | '/media'
    | '/nav'
    | '/products'
    | '/seo'
    | '/settings'
    | '/pages/$page'
    | '/api/public/content/nav'
    | '/api/public/content/site-settings'
    | '/api/public/products/$slug'
    | '/api/public/diaries'
    | '/api/public/products'
    | '/api/public/content/page/$pageKey'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/diaries'
    | '/_authenticated/integration'
    | '/_authenticated/media'
    | '/_authenticated/nav'
    | '/_authenticated/products'
    | '/_authenticated/seo'
    | '/_authenticated/settings'
    | '/_authenticated/pages/$page'
    | '/api/public/content/nav'
    | '/api/public/content/site-settings'
    | '/api/public/products/$slug'
    | '/api/public/diaries/'
    | '/api/public/products/'
    | '/api/public/content/page/$pageKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicContentNavRoute: typeof ApiPublicContentNavRoute
  ApiPublicContentSiteSettingsRoute: typeof ApiPublicContentSiteSettingsRoute
  ApiPublicProductsSlugRoute: typeof ApiPublicProductsSlugRoute
  ApiPublicDiariesIndexRoute: typeof ApiPublicDiariesIndexRoute
  ApiPublicProductsIndexRoute: typeof ApiPublicProductsIndexRoute
  ApiPublicContentPagePageKeyRoute: typeof ApiPublicContentPagePageKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diaries': {
      id: '/_authenticated/diaries'
      path: '/diaries'
      fullPath: '/diaries'
      preLoaderRoute: typeof AuthenticatedDiariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nav': {
      id: '/_authenticated/nav'
      path: '/nav'
      fullPath: '/nav'
      preLoaderRoute: typeof AuthenticatedNavRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages/$page': {
      id: '/_authenticated/pages/$page'
      path: '/pages/$page'
      fullPath: '/pages/$page'
      preLoaderRoute: typeof AuthenticatedPagesPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/content/nav': {
      id: '/api/public/content/nav'
      path: '/api/public/content/nav'
      fullPath: '/api/public/content/nav'
      preLoaderRoute: typeof ApiPublicContentNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/content/site-settings': {
      id: '/api/public/content/site-settings'
      path: '/api/public/content/site-settings'
      fullPath: '/api/public/content/site-settings'
      preLoaderRoute: typeof ApiPublicContentSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diaries/': {
      id: '/api/public/diaries/'
      path: '/api/public/diaries'
      fullPath: '/api/public/diaries/'
      preLoaderRoute: typeof ApiPublicDiariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/': {
      id: '/api/public/products/'
      path: '/api/public/products'
      fullPath: '/api/public/products/'
      preLoaderRoute: typeof ApiPublicProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$slug': {
      id: '/api/public/products/$slug'
      path: '/api/public/products/$slug'
      fullPath: '/api/public/products/$slug'
      preLoaderRoute: typeof ApiPublicProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/content/page/$pageKey': {
      id: '/api/public/content/page/$pageKey'
      path: '/api/public/content/page/$pageKey'
      fullPath: '/api/public/content/page/$pageKey'
      preLoaderRoute: typeof ApiPublicContentPagePageKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiariesRoute: typeof AuthenticatedDiariesRoute
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedNavRoute: typeof AuthenticatedNavRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPagesPageRoute: typeof AuthenticatedPagesPageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiariesRoute: AuthenticatedDiariesRoute,
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedNavRoute: AuthenticatedNavRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPagesPageRoute: AuthenticatedPagesPageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicContentNavRoute: ApiPublicContentNavRoute,
  ApiPublicContentSiteSettingsRoute: ApiPublicContentSiteSettingsRoute,
  ApiPublicProductsSlugRoute: ApiPublicProductsSlugRoute,
  ApiPublicDiariesIndexRoute: ApiPublicDiariesIndexRoute,
  ApiPublicProductsIndexRoute: ApiPublicProductsIndexRoute,
  ApiPublicContentPagePageKeyRoute: ApiPublicContentPagePageKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
